[package]
name = "rb5009_listener"
version = "0.1.0"
edition.workspace = true

[dependencies]
axum.workspace = true
clap.workspace = true
epicentre_diagnostics = { version = "0.1.0", path = "../epicentre_diagnostics" }
thiserror.workspace = true
tokio.workspace = true

[lints]
workspace = true
